[package]
name = "camp"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
pyo3 = { version = "0.21.2", features = ["extension-module"] }
