[project]
name = "camp"
dependencies = [
    "altair[all]>=5.3.0",
    "fsspec>=2024.6.1",
    "gymnasium[atari,box2d,classic-control,mujoco,toy-text]>=0.29.1",
    "keras>=3.4.1",
    "matplotlib>=3.9.1",
    "numpy>=1.26.4",
    "pandas>=2.2.2",
    "s3fs>=2024.6.1",
    "scikit-learn>=1.5.1",
    "scipy>=1.14.0",
    "seaborn>=0.13.2",
]
requires-python = ">= 3.8"

[project.optional-dependencies]
tensorflow = [
    "tensorflow>=2.17.0",
]
torch = [
    "torch>=2.3.1",
    "torchmetrics>=1.4.0.post0",
    "torch-directml>=0.2.3.dev240715",
]
tree = [
    "catboost>=1.2.5",
    "lightgbm>=4.4.0",
    "xgboost>=2.1.0",
]
vision = [
    "mmcv>=2.2.0",
    "mmdet>=3.3.0",
    "mmengine>=0.10.4",
    "supervision>=0.22.0",
    "timm>=1.0.7",
    "torchvision>=0.18.1",
    "ultralytics>=8.2.67",
]

[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[tool.jupytext]
formats = "py:percent"
notebook_metadata_filter = "-all"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "camp.rs"

[tool.mypy]
cache_dir = ".venv/.mypy_cache"
explicit_package_bases = true
ignore_missing_imports = true
allow_redefinition = true

[tool.pytest.ini_options]
cache_dir = ".venv/.pytest_cache"

[tool.ruff]
cache-dir = ".venv/.ruff_cache"

[tool.ruff.lint]
ignore = ["E731", "E741"]

[tool.ruff.lint.isort]
force-single-line = true

[tool.rye]
managed = true
dev-dependencies = [
    "black>=24.4.2",
    "isort>=5.13.2",
    "jedi-language-server>=0.41.4",
    "jupyterlab-code-formatter>=2.2.1",
    "jupyterlab-git>=0.50.1",
    "jupyterlab-lsp>=5.1.0",
    "jupyterlab>=4.2.3",
    "jupytext>=1.16.2",
    "maturin>=1.7.0",
    "mypy>=1.10.1",
    "pip>=24.1.2",
    "pytest>=8.3.1",
    "ruff>=0.5.1",
]
