[project]
name = "camp"
dependencies = [
    "altair[all]>=5.3.0",
    "gymnasium[atari,box2d,classic-control,mujoco,toy-text]>=0.29.1",
    "matplotlib>=3.9.1",
    "numpy>=1.26.4",
    "pandas>=2.2.2",
    "scikit-learn>=1.5.1",
    "scipy>=1.14.0",
    "seaborn>=0.13.2",
    "tensorflow>=2.16.2",
    "xgboost>=2.1.0",
]
requires-python = ">= 3.8"

[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[tool.jupytext]
formats = "py:percent"
notebook_metadata_filter = "-all"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "camp.rs"

[tool.mypy]
cache_dir = ".venv/.mypy_cache"
ignore_missing_imports = true
allow_redefinition = true

[tool.pytest.ini_options]
cache_dir = ".venv/.pytest_cache"

[tool.ruff]
cache-dir = ".venv/.ruff_cache"

[tool.ruff.lint]
ignore = ["E731", "E741"]

[tool.ruff.lint.isort]
force-single-line = true

[tool.rye]
managed = true
dev-dependencies = [
    "black>=24.4.2",
    "isort>=5.13.2",
    "jedi-language-server>=0.41.4",
    "jupyterlab-code-formatter>=2.2.1",
    "jupyterlab-git>=0.50.1",
    "jupyterlab-lsp>=5.1.0",
    "jupyterlab>=4.2.3",
    "jupytext>=1.16.2",
    "maturin>=1.7.0",
    "mypy>=1.10.1",
    "pip>=24.1.2",
    "pytest>=8.3.1",
    "ruff>=0.5.1",
]
